name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: zyymailurl@gmail.com
        password: admin888
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/dongtai/dongtai-server:latest docker://registry.cn-hangzhou.aliyuncs.com/corpbf/dongtai-server:latest
         skopeo copy docker://docker.io/dongtai/dongtai-engine:latest docker://registry.cn-hangzhou.aliyuncs.com/corpbf/dongtai-engine:latest
         skopeo copy docker://docker.io/dongtai/dongtai-redis:latest docker://registry.cn-hangzhou.aliyuncs.com/corpbf/dongtai-redis:latest
         skopeo copy docker://docker.io/dongtai/dongtai-mysql:latest docker://registry.cn-hangzhou.aliyuncs.com/corpbf/dongtai-mysql:latest
         skopeo copy docker://docker.io/dongtai/dongtai-web:latest docker://registry.cn-hangzhou.aliyuncs.com/corpbf/dongtai-web:latest
         skopeo copy docker://docker.io/dongtai/dongtai-mysql-unittest:latest docker://registry.cn-hangzhou.aliyuncs.com/corpbf/dongtai-mysql-unittest:latest
         skopeo copy docker://docker.io/dongtai/dongtai-logstash:latest docker://registry.cn-hangzhou.aliyuncs.com/corpbf/dongtai-logstash:latest
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
